In [1]:
import torch
import numpy as np

In [2]:
tensor1 = torch.randint(1,10,(3,5,4))
print(tensor1.shape)
print(tensor1)

torch.Size([3, 5, 4])
tensor([[[1, 5, 5, 5],
         [6, 8, 2, 6],
         [8, 7, 9, 1],
         [8, 1, 4, 4],
         [8, 9, 7, 6]],

        [[4, 5, 8, 9],
         [2, 4, 6, 7],
         [6, 7, 1, 1],
         [3, 6, 7, 3],
         [5, 7, 6, 5]],

        [[8, 6, 4, 9],
         [5, 7, 2, 1],
         [3, 4, 6, 4],
         [9, 2, 2, 9],
         [4, 4, 2, 4]]])


In [3]:
print(tensor1.reshape(-1,10))

tensor([[1, 5, 5, 5, 6, 8, 2, 6, 8, 7],
        [9, 1, 8, 1, 4, 4, 8, 9, 7, 6],
        [4, 5, 8, 9, 2, 4, 6, 7, 6, 7],
        [1, 1, 3, 6, 7, 3, 5, 7, 6, 5],
        [8, 6, 4, 9, 5, 7, 2, 1, 3, 4],
        [6, 4, 9, 2, 2, 9, 4, 4, 2, 4]])


In [8]:
labels = [0, 2, 3, 1, 4, 3, 2]
mat = torch.zeros((len(labels),5), dtype=torch.int64)
# for i,label in enumerate(labels):
#     mat[i][label] = 1
mat[torch.arange(0,7), labels] = 1

print(mat)

tensor([[1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0]])
